export const sponsors = [
  {
    href: "https://emdistrict.com/",
    imgSrc: "images/s2s-logo/spon-logo/em.svg",
    alt: "EM District",
    type: "LogoRec",
    tier: "tier-1",
  },
  {
    href: "https://www.ddproperty.com/en",
    imgSrc: "images/s2s-logo/spon-logo/dd.svg",
    alt: "DD Property",
    type: "LogoRec",
    tier: "tier-1",
  },
  {
    href: "https://funcslash.com/styleyeet/",
    imgSrc: "images/s2s-logo/spon-logo/st.svg",
    alt: "StyleYeet",
    type: "LogoSqr",
    tier: "tier-1",
  },
  {
    href: "https://ducklab.co.th/",
    imgSrc: "images/s2s-logo/spon-logo/dl.svg",
    alt: "DuckLab",
    type: "LogoSqr",
    tier: "tier-2-dl",
  },
  {
    href: "https://www.merge.co.th/",
    imgSrc: "images/s2s-logo/spon-logo/merge.svg",
    alt: "Merge",
    type: "LogoRec",
    tier: "tier-2",
  },
  {
    href: "https://nabladigital.com/",
    imgSrc: "images/s2s-logo/spon-logo/nb.svg",
    alt: "Nabla Digital",
    type: "LogoRec",
    tier: "tier-2",
  },
  {
    href: "https://www.deemmi.com/",
    imgSrc: "images/s2s-logo/spon-logo/dm.svg",
    alt: "Deemmi",
    type: "LogoSqr",
    tier: "tier-2",
  },
  {
    href: "https://www.facebook.com/diloproducts/?locale=th_TH",
    imgSrc: "images/s2s-logo/spon-logo/dlo.svg",
    alt: "Dilo Products",
    type: "LogoRec",
    tier: "tier-3",
  },
  {
    href: "https://www.facebook.com/p/Q-Light-Sound-100063757264018/",
    imgSrc: "images/s2s-logo/spon-logo/ql.svg",
    alt: "Q-Light Sound",
    type: "LogoSqr",
    tier: "tier-3",
  },
  {
    href: "https://www.youtube.com/@ApologizeCh122",
    imgSrc: "images/s2s-logo/spon-logo/m7.svg",
    alt: "Apologize Ch",
    type: "LogoSqr",
    tier: "tier-3",
  },
];
